slack_flask:
  build: .
  links:
    - redis
  ports:
    - "9000:9000"
  restart: always
  command: ["app.py"]

honcho:
  build: .
  environment:
    - REDIS_PASSWORD="mypass"
  links:
    - redis
  ports:
    - "8080:8080"
  restart: always
  entrypoint: ["honcho", "start"]

redis:
  image: redis
  environment:
    - REDIS_PASSWORD="mypass"
  expose:
    - "6379"
  volumes_from:
    - redisdata

redisdata:
  image: redis
  command: echo 'Data Container for Redis'
  volumes:
    - /data
