slack_flask:
  build: .
  links:
    - redis
  ports:
    - "9000:9000"
  restart: always
  command: ["app.py"]

traffic_director:
  build: .
  links:
    - redis
  restart: always
  command: ["zeromq.py"]
  volumes:
    - .:/usr/src/app

rq:
  build: .
  links:
    - redis
  restart: always
  entrypoint: ["/env/bin/honcho", "start"]


redis:
  image: redis
  volumes_from:
    - redisdata

redisdata:
  image: redis
  command: echo 'Data Container for Redis'
  volumes:
    - /data
