slack_flask:
  build: .
  links:
    - redis
  ports:
    - "9000:9000"
  restart: always
  command: ["app.py"]

rq:
  build: .
  links:
    - redis
  restart: always
  entrypoint: ["rq", "worker", "-c", "lib.rq-settings"]

redis:
  image: redis
  volumes_from:
    - redisdata

redisdata:
  image: redis
  command: echo 'Data Container for Redis'
  volumes:
    - /data
